Auth:
    resource: ../../src/Controller/AuthController.php
    type: annotation
Admin:
    resource: ../../src/Controller/AdminController.php
    type: annotation
Admin_Event:
    resource: ../../src/Controller/EventController.php
    type: annotation
Registrations:
    resource: ../../src/Controller/RegistrationController.php
    type: annotation
Admin_Organiser:
    resource: ../../src/Controller/OrganiserController.php
    type: annotation
Pages:
    resource: ../../src/Controller/PageController.php
    type: annotation
