Admin:
    resource: ../../src/Controller/AdminController.php
    type: annotation
Registrations:
    resource: ../../src/Controller/RegistrationController.php
    type: annotation
Pages:
    resource: ../../src/Controller/PageController.php
    type: annotation
