auth_login:
  controller: App\Controller\AuthController::login
  path: /login

admin:
  controller: App\Controller\AdminController::index
  path: /admin/

events:
  controller: App\Controller\EventController::index
  path: /events/

page:
  controller: App\Controller\PageController::default
  path: /{slug}
  defaults:
    slug: /